# This file lists tools managed by Rokit, a toolchain manager for Roblox projects.
# For more information, see https://github.com/rojo-rbx/rokit

# New tools can be added by running `rokit add <tool>` in a terminal.

[tools]
wally = "UpliftGames/wally@0.3.2"
argon = "argon-rbx/argon@2.0.25"
lune = "lune-org/lune@0.10.1"
StyLua = "JohnnyMorganz/StyLua@2.1.0"
luau-lsp = "JohnnyMorganz/luau-lsp@1.52.1"
blink = "1axen/blink@0.17.4"
selene = "kampfkarren/selene@0.29.0"
darklua = "seaofvoices/darklua@0.16.0"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
